[project]
name = "listenlearn"
version = "0.1.0"
description = ""
authors = ["Yushin Washio <dev@yuwash.eu>"]
license = "MPL-2.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "appdirs>=1.4.4",
    "edge-tts>=7.0.1",
    "instructor>=1.7.9",
]
